#include <stdio.h>
#include <gmp.h>
#include <time.h>
#include <string.h>
#include <stdlib.h>


/* Key size in bits */
#define KEY_SIZE 1024
/* Max source data size in bytes */
#define MAX_SOURCE_SIZE ((KEY_SIZE - 2) / 8)
/* Key string size */
#define KEY_STRING_SIZE 2048


/*
    Encrypts string with key
    @param buffer Result buffer.
                    Should be at least MAX_SOURCE_SIZE bytes
    @param source source string,
                    Should be less than MAX_SOURCE_SIZE bytes
    @param key: string key
                    Should be valid key generated by generate_keys
                    @see generate_keys()
*/
void encrypt(char *buffer, const char *source, const char *key);

/*
    Decrypts string
    @param buffer Result buffer.
                    Should be at least MAX_SOURCE_SIZE bytes
    @param source source string,
                    Should be less than MAX_SOURCE_SIZE bytes
    @param key: string key
                    Should be valid key generated by generate_keys
                    @see generate_keys()
*/
void decrypt(char *buffer, const char *ciphertext, const char *key);

/*
    Generates key pair
    @param public Public key string buffer
                    Should be at least KEY_STRING_SIZE bytes
    @param private Private key string buffer
                    Should be at least KEY_STRING_SIZE bytes
*/
void generate_keys(char *public, char *private);
